# Generated by Django 6.0.7 on 2026-10-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_banner_contactmessage_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('template', models.CharField(blank=True, max_length=100)),
                ('provider', models.CharField(default='console', max_length=50)),
                ('status', models.CharField(choices=[('sent', 'ارسال شده'), ('failed', 'خطا در ارسال'), ('simulated', 'شبیه\u200cسازی شده')], db_index=True, default='simulated', max_length=20)),
                ('provider_msg_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
